### ISSUE TITLE
Inference model

### ISSUE THREAD

**Issue by Augusthyq** [cwchenwang/outdoor-nerf-depth#1]
Hello, thank you for your good job. I want to use a trained model for rendering a small dataset and build a continuous scene. How can I do that?

**Comment by cwchenwang** [comment]
Hi, thank you for reaching out. Do you mean rendering on the scenes that we used for training?

**Comment by Augusthyq** [comment]
> Hi, thank you for reaching out. Do you mean rendering on the scenes that we used for training?

Thank you for your reply. Yes, I have trained the ngp-depth for kitti. How can I use the trained weights to rendering on the scenes.

**Comment by MaxChanger** [comment]
Hi @Augusthyq , sorry for the late reply. It is easier to use ngp-depth to render videos. Only slight modifications to the training code are required. You only need to make the following modifications to render the results. Running command is similar to training
```shell
python valid.py --root_dir $ROOT_DIR \
                --scale $SCALE \
                --mod_ratio $MOD_RATIO \
                --eval_lpips \
                --depth_loss_w $DEPTH_LOSS_WEIGHT \
                --depth_folder $DEPTH_DIR \
                --check_val_every_n_epoch 1 \
                --batch_size $BS \
                --exp_name OnlineScale_mod" \
                --val_only \
                --ckpt_path epoch29.ckpt
```
<img width="1607" alt="image" src="https://github.com/cwchenwang/outdoor-nerf-depth/assets/35401968/9516287c-10ee-4c2d-94fb-7e5216312233">

**Comment by Augusthyq** [comment]
> Hi @Augusthyq , sorry for the late reply. It is easier to use ngp-depth to render videos. Only slight modifications to the training code are required. You only need to make the following modifications to render the results. Running command is similar to training
> 
> ```shell
> python valid.py --root_dir $ROOT_DIR \
>                 --scale $SCALE \
>                 --mod_ratio $MOD_RATIO \
>                 --eval_lpips \
>                 --depth_loss_w $DEPTH_LOSS_WEIGHT \
>                 --depth_folder $DEPTH_DIR \
>                 --check_val_every_n_epoch 1 \
>                 --batch_size $BS \
>                 --exp_name OnlineScale_mod" \
>                 --val_only \
>                 --ckpt_path epoch29.ckpt
> ```
> 
> <img alt="image" width="1607" src="https://private-user-images.githubusercontent.com/35401968/308149442-9516287c-10ee-4c2d-94fb-7e5216312233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzY2NDYsIm5iZiI6MTcwOTAzNjM0NiwicGF0aCI6Ii8zNTQwMTk2OC8zMDgxNDk0NDItOTUxNjI4N2MtMTBlZS00YzJkLTk0ZmItN2U1MjE2MzEyMjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEyMTkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNThmMjc0YWI4MjM2NTI2MzYxNzZjNWMyODU4YTJmNTMwY2IyYmI3MzY0NWZjYjMwNTY1MGZjNjAwN2IzZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.15iyo4MYvjKbjQ3Z15eOUkVOn7pxSjtpUdNawe0bqwY">

Thank you for your reply. I do that. But I find another question. The trained model can only validate on the same dataset  which it is trained. When I try another dataset, it fails. Can the model inference a different dataset? 
![2](https://github.com/cwchenwang/outdoor-nerf-depth/assets/74721580/6cd19f73-a7bd-4beb-a57c-6f8d11d6e1bb)

**Comment by cwchenwang** [comment]
@Augusthyq Hi, I think we cannot evaluate the model on a different dataset because NeRF is a per-scene optimization method.

**Comment by Augusthyq** [comment]
> @Augusthyq Hi, I think we cannot evaluate the model on a different dataset because NeRF is a per-scene optimization method.

I see. Thank you very much.
